### ISSUE TITLE
[otel] Wrong example port

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/docs#14]
In `otel` config example the `endpoint` has value `endpoint: 127.0.0.1:4317`
https://docs.roadrunner.dev/docs/logging-and-observability/otel#configuration

If I use 4317 port then rr show this error. If I use 4318 it's works fine. 

```
2024/06/06 10:05:09 traces export: Post "http://collector:4317/v1/traces": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"
```

https://github.com/roadrunner-server/docs/blob/f8a8a7f80c10985e6861d0dc001344dd9ef6d251/lab/otel.md?plain=1#L90

I thing there is typo in otel config example.

**Comment by rustatian** [comment]
Hey @gam6itko 👋 
Ports are correct. 4317 is used for gRPC, 4318: http.
ref: https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/

**Comment by gam6itko** [comment]
I understand what 4317 for gRPC. But rr.http shows error with it!

I see mismatch for OTEL_EXPORTER_OTLP_ENDPOINT example
https://github.com/roadrunner-server/docs/blob/f8a8a7f80c10985e6861d0dc001344dd9ef6d251/lab/otel.md?plain=1#L59
https://github.com/roadrunner-server/docs/blob/f8a8a7f80c10985e6861d0dc001344dd9ef6d251/lab/otel.md?plain=1#L205
https://github.com/roadrunner-server/docs/blob/f8a8a7f80c10985e6861d0dc001344dd9ef6d251/lab/otel.md?plain=1#L223
